### ISSUE TITLE
Feature 

### ISSUE THREAD

**Issue by kclinsd** [poweredbyme13/rx-tx-simple#1]
This project is very interesting to try, is this full proportional speed and steering? then can you provide a picture of the wiring if using a switch and also a charging path for the battery. Thank you

**Comment by poweredbyme13** [comment]
hey kclinsd!
yes it’s fully proportional steering and acceleration 
I’ll update the page and add wiring diagram

**Comment by poweredbyme13** [comment]
> This project is very interesting to try, is this full proportional speed and steering? then can you provide a picture of the wiring if using a switch and also a charging path for the battery. Thank you

PCB diagram added
https://github.com/poweredbyme13/rx-tx-simple?tab=readme-ov-file#pcb-diagram
